### ISSUE TITLE
Need a flag for unlimited gas

### ISSUE THREAD

**Issue by Rexagon** [tonlabs/TON-SDK#220]
Due to the [hardcoded](https://github.com/tonlabs/TON-SDK/blob/master/ton_sdk/src/local_tvm.rs#L110-L114) gas limit some heavy `get` methods can't be executed. For example `getVotesPerJuror` in FreeTonContest contract. It fails with error `Local run failed: VM Exception: out of gas, code 13, value: 1000000026`.
Maybe additional flag to disable gas limit will be useful.

**Comment by elasticLove1** [comment]
The limit is 1 billion gas, if your contract requires more for local execution, with very high probability there is a bug in the contract.
We can add this feature but, in case of contract bug SDK will just hang forever without any response.

**Comment by Rexagon** [comment]
Oh, I think you're right, it really was a bug and contract was in wrong state. In that case this feature is not necessary. Thanks
