### ISSUE TITLE
[minor stuff] api.json update for tag

### ISSUE THREAD

**Issue by andy-a-o** [tonlabs/TON-SDK#308]
Tag 1.5.1 created, but `api.json` still contains version 1.5.0. 

Expected is: `api.json` to contain the exact tag version. 

Possible solution is to re-generate `api.json` before creating new tag (via some pipeline script).

**Comment by elasticLove1** [comment]
Thank you for this note, we are gradually automating CI/CD for v1, will definitely do that in the next steps
