### ISSUE TITLE
Cell Encoding

### ISSUE THREAD

**Issue by melsomino** [tonlabs/TON-SDK#347]
**Status: Approved** 

# Problem

In some cases users want to build raw cells (BOCs) using low level TON primitives to pass them to contracts to decode them in contracts. Current client library hasn't such functions.

# Solution

Provide feature for cell building:

- `boc.encode_builder` – builds cell using builder write sequence.

## Encode Builder String

```rust
/// Builder write commands.
enum BuilderWrite {
    /// Writes integer.
    Integer {
        /// Bit size of the value.
        size: u8,
        /// Value:
        /// - `Number` containing integer number. e.g. `123`, `-123`.
        /// - Decimal string. e.g. `"123"`, `"-123"`.
        /// - `0x` prefixed hexadecimal string.
        ///   e.g `0x123`, `0X123`, `-0x123`.
        /// If 
        value: Value
    },
    /// Writes bit string.
    BitString {
        /// Bit size. If `size` is zero than `buffer` contains 
        /// taged bit string.
        size: u16,
        // Buffer contained bit string content.
        // Bits layed out inside buffer in the big endian order.
        // So the first written bit is the least significant 
        // bit of the buffer[0].
        buffer: String,
    },
    /// Writes ref to nested cell
    Cell {
        /// Writes cell content
        write: Vec<BuilderWrite>,
    }
}

struct ParamsOfEncodeBuilder {
    write: Vec<BuilderWrite>,
    boc_cache: BocCacheType,
}

struct ResultOfEncodeBuilderString {
    boc: String,
}

// boc module
fn encode_builder(
    context,
    params: ParamsOfEncodeBuilder,
) -> ClientResult<ResultOfEncodeBuilder> {}

```

Wrapper library must defines helper constructors for write commands:

```tsx
b0, b1, bit(true | false)
uint(size, value), u2(value)..u256(value)
int(size, value), i2(value)..i256(value)
bits(buffer, size?), utf8(text)
```
JS Example:
```tsx
const boc = (await client.boc.encode_boc({
    write: [
        u8(12), i32(12345),
        u256(0x478321746387264738674623746372864783267812),
        b1(), cell([u8(13)]),
    ]
})).boc;
```

**Comment by NoamDev** [comment]
I see the need, but string builders do not make sense since the values usually aren't constant.
It'd be better to have something like:
encodeBoc([uint(5), utf8("TEXT"), cell(hashmap()))
or alternatively, something json based (this would allow eaiser porting).
As matter of fact I think it might be best to have it json based but add an interface like I suggested above.

**Comment by pavlovdog** [comment]
@NoamDev I agree with you! As an example of the syntax, I propose to look at the Ethereum's web3 way to encode list of different Solidity types into single bytes sequence - `web3.eth.abi.encodeParameters` ([docs](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-abi.html#id6)):

```
web3.eth.abi.encodeParameters(['uint256','string'], ['2345675643', 'Hello!%']);
> "0x000000000000000000000000000000000000000000000000000000008bd02b7b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000748656c6c6f212500000000000000000000000000000000000000000000000000"
```

It's easy to imagine, how it's gonna look for TON BOC encoding:

```
await client.boc.encode_boc({
  types: ['uin256', 'int8', 'bool', 'TvmCell'],
  values: [123, -12, true, 'ZXhhbXBsZQo=']
})
```

@melsomino @NoamDev What do you think?

**Comment by melsomino** [comment]
I have rewritten proposal.
Waiting for the new comments.
@NoamDev @pavlovdog
