### ISSUE TITLE
Can't build web version if not authenticated on github with SSH key

### ISSUE THREAD

**Issue by vird** [tonlabs/TON-SDK#80]
Steps to reproduce

    git clone https://github.com/tonlabs/TON-SDK
    cd TON-SDK/ton_client/platforms/ton-client-web/
    node build.js

Output

    ton-client-web# node build.js
        Updating crates.io index
        Updating git repository `https://github.com/tonlabs/bip39-rs.git`
        Updating git repository `https://github.com/tonlabs/ton-labs-block.git`
        Updating git repository `https://github.com/tonlabs/ton-labs-types.git`
        Updating git repository `https://github.com/tonlabs/ton-labs-vm.git`
        Updating git repository `https://github.com/tonlabs/ton-labs-abi.git`
        Updating git repository `ssh://git@github.com/tonlabs/ton-executor.git`
    error: failed to load source for a dependency on `ton_executor`
    
    Caused by:
      Unable to update ssh://git@github.com/tonlabs/ton-executor.git
    
    Caused by:
      failed to clone into: /root/.cargo/git/db/ton-executor-655470c1b050fd42
    
    Caused by:
      failed to authenticate when downloading repository
    attempted ssh-agent authentication, but none of the usernames `git` succeeded
    
    Caused by:
      error authenticating: no auth sock variable; class=Ssh (23)
    undefined

env info

    uname -a
    Linux vird-MS-7881 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
    rustc -V
    rustc 1.40.0 (73528e339 2019-12-16)
    node -v
    v12.13.0

nodejs installed with nvm, rust with rustup

**Comment by Futurizt** [comment]
Checking now, thank you.

**Comment by elasticLove1** [comment]
Will be fixed in a couple days, thanks

**Comment by AlexeyVavilin** [comment]
@vird Now you can use `node build.js --open` command to build SDK core using only open source dependencies. Resulting binaries will contain the same functions as full version except fee calculation functions which require `ton-executor` dependency.
P.S. `ton-executor` will be opensourced some time.
